---

version: '3'

tasks:
  a:
    cmds:
      - pigeon a/a.peg > a/a_parser.go
      - go test -v ./a
  jsonnumber:
    cmds:
      - pigeon jsonnumber/jsonnumber.peg > jsonnumber/jsonnumber_parser.go
      - go test -v ./jsonnumber
  wordcount:
    cmds:
      - pigeon wordcount/wordcount.peg > wordcount/wordcount_parser.go
      - go test -v ./wordcount
  csv1:
    cmds:
      - pigeon csv1/csv.peg > csv1/csv_parser.go
      - go test -v ./csv1
  csv2:
    cmds:
      - pigeon csv2/csv.peg > csv2/csv_parser.go
      - go test -v ./csv2
  csv3:
    cmds:
      - pigeon csv3/csv.peg > csv3/csv_parser.go
      - go test -v ./csv3
