---

version: '3'

tasks:
  a:
    cmds:
      - pigeon a/a.peg > a/a_parser.go
      - go test -v ./a
  jsonnumber:
    cmds:
      - pigeon jsonnumber/jsonnumber.peg > jsonnumber/jsonnumber_parser.go
      - go test -v ./jsonnumber
  wordcount:
    cmds:
      - pigeon wordcount/wordcount.peg > wordcount/wordcount_parser.go
      - go test -v ./wordcount
