---

version: '3'

tasks:
  # a_old:
  #   silent: true
  #   cmds:
  #     - pigeon a/a.peg > a/a.go
  #     - go run ./a aaa
  a:
    cmds:
      - pigeon a/a.peg > a/a_parser.go
      - go test -v ./a
  wordlist:
    cmds:
      - pigeon wordlist/wordlist.peg > wordlist/wordlist_parser.go
      - go test -v ./wordlist
  wordcount:
    cmds:
      - pigeon wordcount/wordcount.peg > wordcount/wordcount_parser.go
      - go test -v ./wordcount
